In [13]:
import pandas as pd 
df = pd.read_csv(r'C:\Users\rajas\Downloads\customer_shopping_behavior.csv')

In [12]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [19]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [21]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [25]:
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [27]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [40]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [41]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [52]:
df = df.rename(columns={
    'customer_id': 'id_client',
    'âge': 'age',
    'gender': 'sexe',
    'item_purchased': 'article_achete',
    'category': 'categorie',
    'purchase_amount': 'montant_achat',
    'location': 'localisation',
    'size': 'taille',
    'color': 'couleur',
    'season': 'saison',
    'review_rating': 'note_avis',
    'subscription_status': 'statut_abonnement',
    'shipping_type': 'type_livraison',
    'discount_applied': 'remise_appliquee',
    'promo_code_used': 'code_promo_utilise',
    'previous_purchases': 'achats_precedents',
    'payment_method': 'mode_paiement',
    'frequency_of_purchases': 'frequence_achats'
})

In [53]:
df.columns

Index(['id_client', 'age', 'sexe', 'article_acheté', 'catégorie',
       'montant_achat', 'localisation', 'taille', 'couleur', 'saison',
       'note_avis', 'statut_abonnement', 'type_livraison', 'remise_appliquée',
       'code_promo_utilisé', 'achats_précédents', 'mode_paiement',
       'fréquence_achats'],
      dtype='object')

In [60]:
labels = ['jeune-adulte', 'adulte', 'age-moyen','personne-agee']
df['groupe_age'] = pd.qcut(df['age'], q=4, labels=labels)

In [61]:
df[['age','groupe_age']].head(10)

   age     groupe_age
0   55      age-moyen
1   19   jeune-adulte
2   50      age-moyen
3   21   jeune-adulte
4   45      age-moyen
5   46      age-moyen
6   63  personne-agee
7   27   jeune-adulte
8   26   jeune-adulte
9   57      age-moyen

In [70]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-weekly': 14,
    'Annually': 365,
    'Every 3 months': 90
}
df['frequence_achats_jours'] = df['fréquence_achats'].map(frequency_mapping)

In [71]:
df[['frequence_achats_jours','fréquence_achats']].head(10)

   frequence_achats_jours fréquence_achats
0                    14.0      Fortnightly
1                    14.0      Fortnightly
2                     7.0           Weekly
3                     7.0           Weekly
4                   365.0         Annually
5                     7.0           Weekly
6                    90.0        Quarterly
7                     7.0           Weekly
8                   365.0         Annually
9                    90.0        Quarterly

In [75]:
df['frequence_achats_jours'] = df['frequence_achats_jours'].fillna(0).astype(int)

In [76]:
df[['frequence_achats_jours','fréquence_achats']].head(10)

   frequence_achats_jours fréquence_achats
0                      14      Fortnightly
1                      14      Fortnightly
2                       7           Weekly
3                       7           Weekly
4                     365         Annually
5                       7           Weekly
6                      90        Quarterly
7                       7           Weekly
8                     365         Annually
9                      90        Quarterly

In [78]:
df[['remise_appliquée',
       'code_promo_utilisé']].head(10)

  remise_appliquée code_promo_utilisé
0              Yes                Yes
1              Yes                Yes
2              Yes                Yes
3              Yes                Yes
4              Yes                Yes
5              Yes                Yes
6              Yes                Yes
7              Yes                Yes
8              Yes                Yes
9              Yes                Yes

In [83]:
(df['remise_appliquée'] == df['code_promo_utilisé']).all()

np.True_

In [84]:
df=df.drop('code_promo_utilisé',axis=1)

In [85]:
df.columns

Index(['id_client', 'age', 'sexe', 'article_acheté', 'catégorie',
       'montant_achat', 'localisation', 'taille', 'couleur', 'saison',
       'note_avis', 'statut_abonnement', 'type_livraison', 'remise_appliquée',
       'achats_précédents', 'mode_paiement', 'fréquence_achats', 'groupe_age',
       'frequence_achats_jours'],
      dtype='object')

In [91]:
pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\rajas\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pyodbc in c:\users\rajas\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\rajas\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rajas\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sqlalchemy import create_engine
import pandas as pd

server = "yo"
database = "project1"

connection_string = (
    "mssql+pyodbc://"
    f"{server}/{database}"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
)

engine = create_engine(connection_string)

df.to_sql(
    name="customer_shopping_behavior",
    con=engine,
    schema="dbo",
    if_exists="replace",
    index=False
)

print("Uploaded")